spring:
  h2:
    console:
      enabled: true
      path: /login

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./login
    username: sa
    password:

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret: server!@#

logging:
  level:
    root: info
    org:
      hibernate:
        sql: debug
        type: trace